from datetime import datetime
current_time=datetime.now()
print(current_time)
format_1=current_time.strftime("%Y-%m-%d , %H:%M:%S")
print(format_1)
format_2=current_time.strftime("")
print(format_2)
format_3=current_time.strftime("%A,%B %d,%Y")
print(format_3)
format_4=current_time.strftime("%A,%B %d,%Y %H:%M:%S %p")
print(format_4)
format_5=current_time.strftime("%a-%b-%d %H:%M:%S %Z %Y")
print(format_5)
format_6=current_time.strftime("%Z")
print(format_6)
current_date=current_time.date()
print(current_date)
format_7=current_time.time()
print(format_7)
format_8=current_time.month
print(format_8)
format_9=current_time.year
print(format_9)
